#!/bin/sh

set -e

GETURL="http://localhost:8080/theothertodolist/rest/list.txt"

PUTURL="http://localhost:8080/theothertodolist/rest/save.txt"

# TODO: Has potential issues if $HOME is shared by multiple hosts
TNAME="$HOME/.todo.tmp-$$.json"

curl --silent -H "Accept: text/plain" --output "$TNAME" "$GETURL"

$EDITOR "$TNAME"

echo
curl -H "Content-Type: text/plain" -X POST -d "@$TNAME" "$PUTURL"
echo

